# Generated by Django 5.0 on 2023-12-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_client_email_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
