# Generated by Django 5.0 on 2023-12-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_services_services_services_services_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='services_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
