# Generated by Django 5.0 on 2023-12-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_timeslot_date_alter_timeslot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
