# Generated by Django 5.0 on 2023-12-19 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_timeslot_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
