# Generated by Django 5.0 on 2023-12-19 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_timeslot_date_remove_timeslot_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='date_time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
